"""R14: markdown is generated from YAML, byte-stable, and staleness is detected."""

from __future__ import annotations

SECTIONS = [
    "## Reference images",
    "## Colour palette",
    "## Visual elements",
    "## Typography",
    "## Composition rules",
    "## Layout",
    "## Prompt fragment",
    "## Best for",
    "## Recommended pairings",
]


def test_render_docs_writes_catalogue_and_members(iig3d, tmp_catalogue):
    written = iig3d.render_docs(tmp_catalogue)
    names = sorted(p.relative_to(tmp_catalogue.root).as_posix() for p in written)
    assert names[0] == "docs/CATALOGUE.md"
    assert len(names) == 13 and all(n.startswith("docs/members/3d-") for n in names[1:])
    catalogue = (tmp_catalogue.root / "docs" / "CATALOGUE.md").read_text()
    assert "| `3d-slab-stack` |" in catalogue and "| `linear-progression` | `3d-disc-timeline` |" in catalogue
    assert "#1FB5C8" in catalogue and "industrial-3d" in catalogue


def test_member_doc_sections(iig3d, tmp_catalogue):
    iig3d.render_docs(tmp_catalogue)
    text = (tmp_catalogue.root / "docs" / "members" / "3d-disc-timeline.md").read_text()
    assert text.startswith("# 3d-disc-timeline\n")
    for heading in SECTIONS:
        assert heading in text, heading
    assert "| `ref-03-disc-chain-track.jpg` |" in text and "clean" in text
    assert tmp_catalogue.member("3d-disc-timeline").prompt_fragment in text
    assert "- `linear-progression`: refs 03, 01" in text
    assert "generated by `iig3d.py docs`" in text.lower()


def test_byte_stable(iig3d, tmp_catalogue):
    iig3d.render_docs(tmp_catalogue)
    first = {p: p.read_bytes() for p in (tmp_catalogue.root / "docs").rglob("*.md")}
    iig3d.render_docs(tmp_catalogue)
    second = {p: p.read_bytes() for p in (tmp_catalogue.root / "docs").rglob("*.md")}
    assert first == second


def test_stale_docs_detected(iig3d, tmp_catalogue):
    iig3d.render_docs(tmp_catalogue)
    assert iig3d.stale_docs(tmp_catalogue) == []
    member_yaml = tmp_catalogue.root / "catalogue" / "members" / "3d-hex-cluster.yaml"
    member_yaml.write_text(member_yaml.read_text().replace("backdrop: White to pale grey", "backdrop: Pale grey"))
    cat = iig3d.load_catalogue(tmp_catalogue.root)
    stale = iig3d.stale_docs(cat)
    assert stale and any("3d-hex-cluster.md" in s for s in stale)
    assert any(s.startswith("docs stale:") for s in stale)


def test_missing_docs_are_stale(iig3d, tmp_catalogue):
    import shutil

    shutil.rmtree(tmp_catalogue.root / "docs", ignore_errors=True)
    stale = iig3d.stale_docs(tmp_catalogue)
    assert len(stale) == 13
